/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import oracle.jdbc.OracleDriver;

/**
 *
 * @author codyc
 */
public class DatabaseViews extends javax.swing.JFrame {

     static Connection conn;
    static Statement stmt;
    static BufferedReader keyboard;
    /**
     * Creates new form DatabaseViews
     */
    public DatabaseViews() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Please enter your name to look up your purchased cars: ");

        jButton1.setText("Find Best Dealer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Find the Total Sales of Each Location");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Find the Number of Cars of Each Make Sold");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel2.setText("Result:");

        jButton4.setText("Search");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(34, 34, 34)
                .addComponent(jButton3)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
//SELECT owners.first_name, owners.last_name, cars.make, cars.model FROM OWNEDCARS JOIN Cars ON cars.id = OWNEDCARS.CAR_ID JOIN Owners ON owners.id = OWNEDCARS.OWNER_ID ORDER BY owners.first_name;
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String username = "S25_crc140", password = "xs43qECa";
        String ename;
        int original_empno = 0;
        int empno;

        keyboard = new BufferedReader(new InputStreamReader(System.in));

        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            System.out.println("Registered the driver...");
            conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@oracle2.wiu.edu:1521/orclpdb1",
                username, password
            );
            System.out.println("logged into oracle as " + username);
            conn.setAutoCommit(false);
            stmt = conn.createStatement();
            ResultSet rset = stmt.executeQuery("Select * from S25_MW222.bDealer");
            StringBuilder s = new StringBuilder();
            while (rset.next()){
                String input = rset.getString(1);
                String[] parts = input.split(", ");
                String firstName = parts[0].split(": ")[1];
                String lastName = parts[1].split(": ")[1];
                String carsSold = parts[2].split(": ")[1];
                String totalSales = parts[3].split(": ")[1];
                String output = firstName + " " + lastName + " sold " + carsSold + " cars and brought in $" + totalSales + ". ";
                s.append(output);
            }
            jLabel2.setPreferredSize(new Dimension(300, 60));
            jLabel2.setText("<html>" + s.toString() + "</html>");
            rset.close();
        } 
        catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String username = "S25_crc140", password = "xs43qECa";
        String ename;
        int original_empno = 0;
        int empno;

        keyboard = new BufferedReader(new InputStreamReader(System.in));

        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            System.out.println("Registered the driver...");
            conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@oracle2.wiu.edu:1521/orclpdb1",
                username, password
            );
            System.out.println("logged into oracle as " + username);
            conn.setAutoCommit(false);
            stmt = conn.createStatement();
            ResultSet rset = stmt.executeQuery("SELECT * FROM S25_MW222.locationProfit FETCH FIRST 10 ROWS ONLY");
            StringBuilder s = new StringBuilder();
            while (rset.next()){
                String o = rset.getString(1);
                System.out.println(o);
                String n = rset.getString(2);
                System.out.println(n);
                String[] p = n.split("tot_r");
                String carsSold = p[0].split(": ")[1];
                String revenue = p[1].split(": ")[1];
                carsSold = carsSold.replaceAll("(?<!^)\"(?!$)", "");
                revenue = revenue.replaceAll("(?<!^)\"(?!$)", "");
                String finale = o + " sold " + carsSold + " cars and made $" + revenue + ". ";
                System.out.println(o);
                System.out.println(n);
                s.append(finale);
            }
            jLabel2.setPreferredSize(new Dimension(300, 60));
            jLabel2.setText("<html>" + s.toString() + "</html>");
            rset.close();
        } 
        catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String username = "S25_crc140", password = "xs43qECa";
        String ename;
        int original_empno = 0;
        int empno;

        keyboard = new BufferedReader(new InputStreamReader(System.in));

        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            System.out.println("Registered the driver...");
            conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@oracle2.wiu.edu:1521/orclpdb1",
                username, password
            );
            System.out.println("logged into oracle as " + username);
            conn.setAutoCommit(false);
            stmt = conn.createStatement();
            ResultSet rset = stmt.executeQuery("SELECT * FROM S25_MW222.locationProfit FETCH FIRST 10 ROWS ONLY");
            StringBuilder s = new StringBuilder();
            while (rset.next()){

            }
        }
            catch (Exception e) {
            }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String name = jTextField1.getText();
        String[] names = name.split(" ");
        if (name == ""){
            jLabel2.setText("Please write your name.");
        }
        else{
        String username = "S25_crc140", password = "xs43qECa";
        String ename;
        int original_empno = 0;
        int empno;

        keyboard = new BufferedReader(new InputStreamReader(System.in));

        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            System.out.println("Registered the driver...");
            conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@oracle2.wiu.edu:1521/orclpdb1",
                username, password
            );
            System.out.println("logged into oracle as " + username);
            conn.setAutoCommit(false);
            stmt = conn.createStatement();
            ResultSet rset = stmt.executeQuery("SELECT owners.first_name, owners.last_name, cars.make, cars.model, S25_DEO103.payment.balance FROM OWNEDCARS JOIN Cars ON cars.id = OWNEDCARS.CAR_ID JOIN Owners ON owners.id = OWNEDCARS.OWNER_ID JOIN S25_DEO103.payment ON S25_DEO103.payment.car_id = OWNEDCARS.CAR_ID AND S25_DEO103.payment.owner_id = OWNEDCARS.OWNER_ID WHERE owners.first_name = '" + names[0] + "' AND owners.last_name = '" + names[1] + "' ORDER BY owners.first_name");
            StringBuilder s = new StringBuilder();
            while (rset.next()){
                String fname = rset.getString(1);
                System.out.println(fname);
                String lname = rset.getString(2);
                String make = rset.getString(3);
                String model = rset.getString(4);
                String balance = rset.getString(5);
                String finale = fname + " " + lname + ", you own a " + make + " " + model + ", and you still owe $" + balance + " before it is paid off!";
                s.append(finale);
            }
            jLabel2.setPreferredSize(new Dimension(300, 60));
            jLabel2.setText("<html>" + s.toString() + "</html>");
         }
        catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseViews().setVisible(true);
            }
        });
        String s = "tot_cars_sold: '22' tot_revenue: '2250.5'";
            String[] p = s.split("tot_r");
            for (int i = 0; i < p.length; i++){
                System.out.println(p[i]);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
