/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleDriver;

/**
 *
 * @author codyc
 */
public class DatabaseViews extends javax.swing.JFrame {

     static Connection conn;
    static Statement stmt;
    static BufferedReader keyboard;
    /**
     * Creates new form DatabaseViews
     */
    public DatabaseViews() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Find Best Dealer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Find the Total Sales of Each Location");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Find the Number of Cars of Each Make Sold");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Make", "Model", "Payment Left"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Please enter your name and assigned role: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "David O. (Car Owner)", "Maximus W. (Visitor)", "Cody C. (Dealer)", "Kyle S. (Visitor)" }));

        jButton4.setText("Sign In");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)
                        .addGap(81, 81, 81)
                        .addComponent(jButton2)
                        .addGap(124, 124, 124)
                        .addComponent(jButton3)))
                .addGap(55, 55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jTable1.setModel(new DefaultTableModel(
        new Object[][] {}, // initial empty rows
        new String[] {"First Name", "Last Name", "# of Cars Sold", "Total Sales"} // column names
        ));
        DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();
        String username = "S25_crc140", password = "xs43qECa";
        String ename;
        int original_empno = 0;
        int empno;

        keyboard = new BufferedReader(new InputStreamReader(System.in));

        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            System.out.println("Registered the driver...");
            conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@oracle2.wiu.edu:1521/orclpdb1",
                username, password
            );
            System.out.println("logged into oracle as " + username);
            conn.setAutoCommit(false);
            stmt = conn.createStatement();
            ResultSet rset = stmt.executeQuery("Select * from S25_MW222.bDealer");
            StringBuilder s = new StringBuilder();
            while (rset.next()){
                String input = rset.getString(1);
                String[] parts = input.split(", ");
                String firstName = parts[0].split(": ")[1];
                String lastName = parts[1].split(": ")[1];
                String carsSold = parts[2].split(": ")[1];
                String totalSales = parts[3].split(": ")[1];
                String output = firstName + " " + lastName + " sold " + carsSold + " cars and brought in $" + totalSales + ". ";
                s.append(output);
                model2.addRow(new Object[]{firstName, lastName, carsSold, totalSales});
            }
            rset.close();
        } 
        catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jTable1.setModel(new DefaultTableModel(
        new Object[][] {}, // initial empty rows
        new String[] {"Location", "# of Cars Sold", "Total Sales"} // column names
        ));
        DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();
        String username = "S25_crc140", password = "xs43qECa";
        String ename;
        int original_empno = 0;
        int empno;

        keyboard = new BufferedReader(new InputStreamReader(System.in));

        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            System.out.println("Registered the driver...");
            conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@oracle2.wiu.edu:1521/orclpdb1",
                username, password
            );
            System.out.println("logged into oracle as " + username);
            conn.setAutoCommit(false);
            stmt = conn.createStatement();
            ResultSet rset = stmt.executeQuery("SELECT * FROM S25_MW222.locationProfit");
            StringBuilder s = new StringBuilder();
            while (rset.next()){
                String o = rset.getString(1);
                System.out.println(o);
                String n = rset.getString(2);
                System.out.println(n);
                String[] p = n.split("tot_r");
                String carsSold = p[0].split(": ")[1];
                String revenue = p[1].split(": ")[1];
                carsSold = carsSold.replaceAll("(?<!^)\"(?!$)", "");
                revenue = revenue.replaceAll("(?<!^)\"(?!$)", "");
                String finale = o + " sold " + carsSold + " cars and made $" + revenue + ". ";
                s.append(finale);
                model2.addRow(new Object[] {o, carsSold, revenue});
            }
            rset.close();
        } 
        catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
         jTable1.setModel(new DefaultTableModel(
        new Object[][] {}, // initial empty rows
        new String[] {"Make", "Number Sold"} // column names
        ));
        DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();
        String username = "S25_crc140", password = "xs43qECa";
        String ename;
        int original_empno = 0;
        int empno;

        keyboard = new BufferedReader(new InputStreamReader(System.in));

        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            System.out.println("Registered the driver...");
            conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@oracle2.wiu.edu:1521/orclpdb1",
                username, password
            );
            System.out.println("logged into oracle as " + username);
            conn.setAutoCommit(false);
            stmt = conn.createStatement();
            ResultSet rset = stmt.executeQuery("SELECT * From S25_MW222.CarSold");
            StringBuilder s = new StringBuilder();
            while (rset.next()){
                String fname = rset.getString(1);
                String lname = rset.getString(2);
                model2.addRow(new Object[]{fname, lname});
            }
         }
        catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
       jTable1.setModel(new DefaultTableModel(
        new Object[][] {}, // initial empty rows
        new String[] {"Make", "Number Sold"} // column names
        ));
        DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();
        String username = "S25_crc140", password = "xs43qECa";
        String ename;
        int original_empno = 0;
        int empno;

        keyboard = new BufferedReader(new InputStreamReader(System.in));

        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            System.out.println("Registered the driver...");
            conn = DriverManager.getConnection(
                "jdbc:oracle:thin:@oracle2.wiu.edu:1521/orclpdb1",
                username, password
            );
            System.out.println("logged into oracle as " + username);
            conn.setAutoCommit(false);
            stmt = conn.createStatement();
            ResultSet rset = stmt.executeQuery("SELECT * From S25_MW222.CarSold");
            StringBuilder s = new StringBuilder();
            while (rset.next()){
                String fname = rset.getString(1);
                String lname = rset.getString(2);
                model2.addRow(new Object[]{fname, lname});
            }
         }
        catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseViews().setVisible(true);
            }
        });
        String s = "tot_cars_sold: '22' tot_revenue: '2250.5'";
            String[] p = s.split("tot_r");
            for (int i = 0; i < p.length; i++){
                System.out.println(p[i]);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
